
RUN apt-get install libaio1
RUN apt-get install build-essential libsqlite3-dev zlib1g-dev
RUN apt-get install git
RUN git clone https://github.com/mapbox/tippecanoe.git
RUN cd tippecanoe
RUN make
RUN make install
RUN cd ..
